import pandas as pd
from prometheus_api_client import PrometheusConnect
from datetime import datetime, timedelta
import time
import os
import re

# --- Configuration ---
PROMETHEUS_URL = os.environ.get("PROMETHEUS_URL", "http://localhost:9094")
NODES = [f"node-{i}" for i in range(1, 16)]

# Time range to query (query the last 30 minutes)
START_TIME = datetime.now() - timedelta(minutes=30) 
END_TIME = datetime.now()
STEP_SIZE = '10s' # Higher resolution for short scenario windows

# --- New Function: Get Fault Map from Host Environment ---
def get_fault_map():
    """
    Reads the .env file generated by the scenario runner to create a map of 
    {node_id: fault_type}. This ensures we label the data correctly based on
    the most recent experiment configuration.
    """
    fault_map = {}
    env_file = './.env'
    
    if os.path.exists(env_file):
        with open(env_file, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#'):
                    # Check for NODE_X_FAULT=fault_type
                    match = re.match(r"NODE_(\d+)_FAULT=(.+)", line)
                    if match:
                        node_number = match.group(1)
                        fault_type = match.group(2)
                        node_id = f"node-{node_number}"
                        fault_map[node_id] = fault_type.lower()
    else:
        print(f"WARNING: {env_file} not found. Defaulting all nodes to 'benign'.")
    
    # Default all nodes not found in file to benign
    for node in NODES:
        if node not in fault_map:
            fault_map[node] = 'benign'
            
    return fault_map

# --- Prometheus Query Language (PQL) ---
def get_pql_queries(node):
    """
    Returns the PQL queries for latency (200 OK only), 500-error count, CPU, and Memory.
    """
    target_instance = f'{node}:8000' 
    
    # Query 1: Average Latency (histogram doesn't have status label)
    latency_query = f"""
    avg_over_time(request_latency_seconds_sum{{instance="{target_instance}"}}[{STEP_SIZE}]) 
    / 
    avg_over_time(request_latency_seconds_count{{instance="{target_instance}"}}[{STEP_SIZE}])
    """
    
    # Query 2: External Error Count (LB perspective) 
    # This captures validation failures and timeouts that the node might hide.
    error_count_query = f"""
    sum(increase(lb_routed_requests_total{{selected_node="{node}", status!="200"}}[{STEP_SIZE}]))
    """

    # Query 3: CPU Usage (use the realistic simulation metric)
    cpu_query = f"""
    node_cpu_usage_percent{{instance="{target_instance}"}} / 100
    """
    
    # Query 4: Memory Usage (use the realistic simulation metric, convert to MB)
    memory_query = f"""
    node_memory_mb{{instance="{target_instance}"}}
    """
    
    return latency_query, error_count_query, cpu_query, memory_query # RETURN ALL FOUR QUERIES

from dotenv import load_dotenv

def fetch_metrics(start_time=None, end_time=None):
    """
    Fetches all metrics from Prometheus for all nodes.
    If start_time and end_time are provided, fetches only that window.
    Otherwise defaults to the last 30 minutes.
    """
    load_dotenv(dotenv_path='./.env', override=True)    
    
    # Define query window
    if start_time is None:
        start_time = datetime.now() - timedelta(minutes=30) 
    if end_time is None:
        end_time = datetime.now()
        
    # 1. CRITICAL: Get the ground truth fault map first
    fault_map = get_fault_map()
    print(f"\n--- Exporting Window: {start_time} to {end_time} ---")
    print(f"--- Fault Map: {fault_map} ---")

    try:
        prom = PrometheusConnect(url=PROMETHEUS_URL, disable_ssl=True)
    except Exception as e:
        print(f"Failed to connect to Prometheus: {e}")
        return None

    all_data = []

    for node in NODES:
        latency_query, error_count_query, cpu_query, memory_query = get_pql_queries(node)

        try:
            # Fetch Data for the specified window
            latency_data = prom.custom_query_range(query=latency_query, start_time=start_time, end_time=end_time, step=STEP_SIZE)
            error_count_data = prom.custom_query_range(query=error_count_query, start_time=start_time, end_time=end_time, step=STEP_SIZE)
            cpu_data = prom.custom_query_range(query=cpu_query, start_time=start_time, end_time=end_time, step=STEP_SIZE)
            memory_data = prom.custom_query_range(query=memory_query, start_time=start_time, end_time=end_time, step=STEP_SIZE)
            
            # --- Data Processing ---
            
            def extract_values(data):
                values = {}
                if data and data[0].get('values'):
                    for timestamp, value in data[0]['values']:
                        values[timestamp] = float(value) if value not in ('NaN', 'inf', '-inf') else 0.0
                return values

            latency_values = extract_values(latency_data)
            error_count_values = extract_values(error_count_data)
            cpu_values = extract_values(cpu_data)
            memory_values = extract_values(memory_data) # In bytes
            
            # Combine into records
            all_timestamps = set(latency_values.keys()) | set(error_count_values.keys()) | set(cpu_values.keys()) | set(memory_values.keys())

            # 2. Get the correct fault type for this node
            node_fault_type = fault_map.get(node, 'benign')
            
            for timestamp in all_timestamps:
                # Memory is already in MB from the query
                mem_mb = memory_values.get(timestamp, 0.0)
                
                # Use the presence of 500 errors to inform the status code column
                status_code = 500 if error_count_values.get(timestamp, 0) > 0 else 200

                all_data.append({
                    'timestamp': datetime.fromtimestamp(timestamp),
                    'node_id': node,
                    'avg_latency_seconds': latency_values.get(timestamp, 0.0), 
                    'error_500_count': error_count_values.get(timestamp, 0.0), # RAW COUNT
                    'status_code_for_verification': status_code,              # NEW COLUMN (200 or 500)
                    'cpu_usage_rate': cpu_values.get(timestamp, 0.0), 
                    'resident_mem_mb': mem_mb,                
                    'fault_type': node_fault_type # *** FIXED: AUTOMATICALLY LABELED ***
                })

        except Exception as e:
            print(f"Warning: Could not fetch all data for {node}. Error: {e}")
            continue

    if not all_data:
        return None
        
    df = pd.DataFrame(all_data)
    df = df.sort_values(by=['node_id', 'timestamp'])
    
    return df

if __name__ == "__main__":
    
    df = fetch_metrics()
    
    if df is not None and not df.empty:
        filename = f"byzantine_training_data_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
        df.to_csv(filename, index=False)
        print("\n--- DATA COLLECTION SUCCESSFUL & AUTOMATICALLY LABELED ---")
        print(f"Collected {len(df)} data points across {len(NODES)} nodes.")
        print(f"Data saved to: {filename}")
        
        # --- Final Verification ---
        fault_counts = df['fault_type'].value_counts()
        print("\nGround Truth Labels Found in Data:")
        print(fault_counts.to_markdown(numalign="left", stralign="left"))
        
        if len(fault_counts) > 1:
            print("\nSUCCESS: Multiple fault types detected! Your SVM training is now possible.")
        else:
            print("\nWARNING: Only one fault type detected. Ensure you ran `./start_random.sh` in this same terminal session.")
            
    else:
        print("ERROR: Failed to collect data or DataFrame is empty. Ensure Prometheus has collected enough data.")
